version: '3'

services:
  es:
    container_name: es
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}.0"
    networks:
      - es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:   
      - cluster.name=es-cluster
      - node.name=es-node-1
      - path.data=/usr/share/elasticsearch/data
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "${ES_SERVER}/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  kb:
    container_name: kb
    image: "docker.elastic.co/kibana/kibana:${ES_VERSION}.0"
    networks:
      - es
    environment:
    - server.port=127.0.0.1:5601
    - ELASTICSEARCH_HOSTS=${ES_SERVER}
    - xpack.security.enabled=false
    - server.name="kibana"
    ports:
      - "5601:5601"
    depends_on:
      - es
    links: 
      - es
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "${KIBANA_SERVER}/status"]
      interval: 10s
      timeout: 5s
      retries: 5

  cxs:
    container_name: cxs
    image: "cxsizing:latest"
    networks:
      - es
    environment:
    - CUSTOMER=${CUSTOMER}
    - ENV=${ENV}
    - CX_SERVER=${CX_SERVER}
    - CX_USERNAME=${CX_USERNAME}
    - CX_PASSWORD=${CX_PASSWORD}
    - ES_SERVER=${ES_SERVER}
    - ES_VERSION=${ES_VERSION}
    - ES_INDEX_PREFIX=${ES_INDEX_PREFIX}
    - ES_ID_SECRET=${ES_ID_SECRET}
    depends_on:
      - es
      - kb
    links: 
      - es
      - kb
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "${CX_SERVER}"]
networks: 
  es:
    driver: bridge